language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - PIP=pip
        - PYTHON=python
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_x86_64*
        - PIP=pip
        - PYTHON=python
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2

env:
  global:
    - TWINE_USERNAME=benfred
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel setuptools_rust
  - export CIBW_BEFORE_BUILD='pip install setuptools-rust && source {project}/ci/install_rust.sh'
  - export CIBW_SKIP=cp27-*\ cp33-*\ cp34-*\ $cp35-*\ CIBW_SKIP
  - export CIBW_ENVIRONMENT='PATH="$HOME/.cargo/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      $PYTHON -m twine upload wheelhouse/*.whl
    fi
