language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_i686*
    - sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_x86_64*
    - os: osx
      language: generic
      env:
        - CIBW_SKIP=""

env:
  global:
    - TWINE_USERNAME=vlad17
      # Note: TWINE_PASSWORD is set in Travis settings, but only for master

script:
  - mkdir -p $HOME/rust-installer
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o ~/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh -y
  - pip install maturin pytest
  - source $HOME/.cargo/env
  - cargo build
  - cargo test
  - maturin develop
  - pytest
  - maturin build
  - |
    if [[ $TRAVIS_TAG ]] && [ -n "$TWINE_PASSWORD" ]; then
      pip install twine
      python -m twine upload target/wheels/*.whl
    fi
