language: python
jobs:
  include:
    - python: 3.7
      os: linux
      sudo: required
      services:
        - docker

script:
  - mkdir -p $HOME/rust-installer
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o $HOME/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh -y
  - pip install maturin pytest
  - source $HOME/.cargo/env
  - cargo build
  - cargo test
  - maturin develop
  - pytest
  - PYVER=$(python -c 'import sys; print("python{}.{}".format(*sys.version_info[:2]))')
  - echo $PYVER
  - maturin build --interpreter $PYVER
  - |
    if [[ $TRAVIS_TAG ]] && [ -n "$PYPI_TOKEN" ]; then
       docker run --rm -v $(pwd):/io konstin2/maturin publish --no-sdist --username __token__ --password "$PYPI_TOKEN"
    fi
