language: python
jobs:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
      language: generic

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      # https://github.com/PyO3/maturin/commit/08e04985c51a549b2364738b65ce07b073fcb3da#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L70
      python3 -m pip install -U cffi virtualenv	
    fi
  - mkdir -p $HOME/rust-installer
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o $HOME/rust-installer/rustup.sh
  - sh ~/rust-installer/rustup.sh -y
  - pip install maturin pytest
  - source $HOME/.cargo/env
  - cargo build
  - cargo test
  - maturin develop
  - pytest
  - PYVER=$(python -c 'import sys; print("python{}.{}".format(*sys.version_info[:2]))')
  - echo $PYVER
  - maturin build --interpreter $PYVER
  - |
    if [[ $TRAVIS_TAG ]] && [ -n "$TWINE_PASSWORD" ]; then
      pip install twine
      python -m twine upload target/wheels/*.whl
    fi
